"""backup

Revision ID: 7e173b5d4b48
Revises: 
Create Date: 2017-10-23 23:24:50.534707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e173b5d4b48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('catalog', sa.Unicode(length=80), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'roles', ['catalog'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'catalog')
    # ### end Alembic commands ###
